export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const PAGE_INCREMENT = "PAGE_INCREMENT";
export const PAGE_DECREMENT = "PAGE_DECREMENT";
export const PAGE_RESET = "PAGE_RESET";

export const ADD_REVIEW = "ADD_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const FETCH_REVIEWS = "FETCH_REVIEWS";
